name: Testes e Aprovação de PR

on:
  pull_request:
    paths:
      - 'mobile/**'
      - 'backend/**'
    branches:
      - main
      - develop

jobs:
  run-tests:
    name: Executar testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências do mobile
        run: |
          cd mobile
          npm install

      - name: Executar testes do mobile
        run: |
          cd mobile
          npm test

      - name: Instalar dependências do backend
        run: |
          cd backend
          npm install

      - name: Executar testes do backend
        run: |
          cd backend
          npm test

  approval:
    name: Aguardar aprovação
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Esperar aprovação manual
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: marinafagundes  # substitua por outro usuário se necessário
